package badsmells;

/*
 * Smell: Divergent Change
 *
 * This class handles report formatting, SQL generation, and CSV export. Those
 * are different reasons to change, so they should not be forced into one class.
 *
 * Proposed Refactorings:
 * - Extract separate classes for reporting, SQL persistence, and CSV export.
 * - Move fields and methods to the modules that change for the same reason.
 */
public class DivergentChangeExample {
	private String reportTitle = "Exam Results";
	private String reportFooter = "Generated by registrar office";

	private String tableName = "exam_results";
	private String databaseUrl = "jdbc:mysql://localhost:3306/school";

	private String csvSeparator = ",";
	private boolean includeCsvHeader = true;

	public String formatStudentReport(String name, int score) {
		return reportTitle + "\n" + name + ": " + score + "\n" + reportFooter;
	}

	public String buildSqlInsert(String name, int score) {
		return "/* " + databaseUrl + " */ INSERT INTO " + tableName + "(name, score) VALUES ('" + name + "', "
				+ score + ")";
	}

	public String exportCsv(String name, int score) {
		String csv = name + csvSeparator + score;
		if (includeCsvHeader) {
			return "name" + csvSeparator + "score\n" + csv;
		}
		return csv;
	}

	public void clientCode() {
		System.out.println(formatStudentReport("Nino", 95));
		System.out.println(buildSqlInsert("Nino", 95));
		System.out.println(exportCsv("Nino", 95));
	}
}
