package badsmells;

/*
 * Smell:
 * This class mixes report formatting, SQL generation, and CSV export in one
 * place. These are different responsibilities with different reasons to change.
 *
 * Refactorings:
 * - Extracted report formatting into ReportFormatter
 * - Extracted SQL generation into SqlExporter
 * - Extracted CSV export into CsvExporter
 *
 * Why better:
 * Each class now has a single clear responsibility. Changes to reporting,
 * database output, or CSV formatting are localized to the relevant class.
 *
 * Behavior:
 * The observable behavior remains unchanged.
 */
public class DivergentChangeExample {

    static class ReportFormatter {
        private final String reportTitle = "Exam Results";
        private final String reportFooter = "Generated by registrar office";

        public String formatStudentReport(String name, int score) {
            return reportTitle + "\n" + name + ": " + score + "\n" + reportFooter;
        }
    }

    static class SqlExporter {
        private final String tableName = "exam_results";
        private final String databaseUrl = "jdbc:mysql://localhost:3306/school";

        public String buildSqlInsert(String name, int score) {
            return "/* " + databaseUrl + " */ INSERT INTO " + tableName
                    + "(name, score) VALUES ('" + name + "', " + score + ")";
        }
    }

    static class CsvExporter {
        private final String csvSeparator = ",";
        private final boolean includeCsvHeader = true;

        public String exportCsv(String name, int score) {
            String csv = name + csvSeparator + score;
            if (includeCsvHeader) {
                return "name" + csvSeparator + "score\n" + csv;
            }
            return csv;
        }
    }

    public void clientCode() {
        ReportFormatter reportFormatter = new ReportFormatter();
        SqlExporter sqlExporter = new SqlExporter();
        CsvExporter csvExporter = new CsvExporter();

        System.out.println(reportFormatter.formatStudentReport("Nino", 95));
        System.out.println(sqlExporter.buildSqlInsert("Nino", 95));
        System.out.println(csvExporter.exportCsv("Nino", 95));
    }
}
